/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AchievementTrackerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian12 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  gamesFolder: "Games",
  defaultPlatform: "PS5",
  psnNpssoToken: ""
};

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/services/psn-service.ts
var import_obsidian = require("obsidian");
var https = __toESM(require("https"));
var AUTH_BASE_URL = "https://ca.account.sony.com/api/authz/v3/oauth";
var TROPHY_BASE_URL = "https://m.np.playstation.com/api/trophy";
var PsnService = class {
  constructor() {
    this.accessToken = null;
    this.authExpiresAt = 0;
  }
  /**
   * Make an HTTPS GET request without following redirects.
   * Returns the Location header from 3xx responses.
   */
  httpGetNoRedirect(url, headers) {
    return new Promise((resolve, reject) => {
      const parsedUrl = new URL(url);
      const req = https.request(
        {
          hostname: parsedUrl.hostname,
          path: parsedUrl.pathname + parsedUrl.search,
          method: "GET",
          headers
        },
        (res) => {
          res.resume();
          resolve({
            statusCode: res.statusCode || 0,
            headers: res.headers
          });
        }
      );
      req.on("error", reject);
      req.end();
    });
  }
  async authenticate(npssoToken) {
    if (this.accessToken && Date.now() < this.authExpiresAt) return;
    const params = new URLSearchParams({
      access_type: "offline",
      client_id: "09515159-7237-4370-9b40-3806e67c0891",
      redirect_uri: "com.scee.psxandroid.scecompcall://redirect",
      response_type: "code",
      scope: "psn:mobile.v2.core psn:clientapp"
    });
    const authorizeUrl = `${AUTH_BASE_URL}/authorize?${params}`;
    let code = null;
    try {
      const resp = await this.httpGetNoRedirect(authorizeUrl, {
        Cookie: `npsso=${npssoToken}`
      });
      const location = resp.headers.location;
      if (typeof location === "string" && location.includes("code=")) {
        const match = location.match(/code=([^&]+)/);
        if (match) code = match[1];
      }
    } catch (e) {
    }
    if (!code) {
      throw new Error(
        "Failed to retrieve PSN access code. Is your NPSSO token valid?\nGet a new one at https://ca.account.sony.com/api/v1/ssocookie"
      );
    }
    const tokenResp = await (0, import_obsidian.requestUrl)({
      url: `${AUTH_BASE_URL}/token`,
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        Authorization: "Basic MDk1MTUxNTktNzIzNy00MzcwLTliNDAtMzgwNmU2N2MwODkxOnVjUGprYTV0bnRCMktxc1A="
      },
      body: new URLSearchParams({
        code,
        redirect_uri: "com.scee.psxandroid.scecompcall://redirect",
        grant_type: "authorization_code",
        token_format: "jwt"
      }).toString()
    });
    const tokenData = tokenResp.json;
    if (!tokenData.access_token) {
      throw new Error(
        "Failed to obtain PSN access token. " + (tokenData.error_description || tokenData.error || "Unknown error")
      );
    }
    this.accessToken = tokenData.access_token;
    this.authExpiresAt = Date.now() + ((tokenData.expires_in || 3600) - 60) * 1e3;
  }
  async testConnection(npssoToken) {
    this.accessToken = null;
    this.authExpiresAt = 0;
    await this.authenticate(npssoToken);
    return true;
  }
  async apiCall(url) {
    const response = await (0, import_obsidian.requestUrl)({
      url,
      method: "GET",
      headers: {
        Authorization: `Bearer ${this.accessToken}`,
        "Content-Type": "application/json"
      }
    });
    return response.json;
  }
  async fetchUserGames(npssoToken) {
    await this.authenticate(npssoToken);
    const allGames = [];
    let offset = 0;
    const limit = 800;
    while (true) {
      const params = new URLSearchParams({
        limit: String(limit),
        offset: String(offset)
      });
      const url = `${TROPHY_BASE_URL}/v1/users/me/trophyTitles?${params}`;
      const response = await this.apiCall(url);
      for (const title of response.trophyTitles) {
        allGames.push({
          npCommunicationId: title.npCommunicationId,
          npServiceName: title.npServiceName,
          trophyTitleName: title.trophyTitleName,
          trophyTitlePlatform: title.trophyTitlePlatform,
          trophyTitleIconUrl: title.trophyTitleIconUrl,
          progress: title.progress,
          definedTrophies: title.definedTrophies,
          earnedTrophies: title.earnedTrophies
        });
      }
      if (!response.nextOffset || response.trophyTitles.length < limit) {
        break;
      }
      offset = response.nextOffset;
    }
    return allGames.sort(
      (a, b) => a.trophyTitleName.localeCompare(b.trophyTitleName)
    );
  }
  async fetchGameTrophies(npssoToken, game) {
    await this.authenticate(npssoToken);
    const serviceParam = game.npServiceName === "trophy" ? "?npServiceName=trophy" : "";
    const definitionsUrl = `${TROPHY_BASE_URL}/v1/npCommunicationIds/${game.npCommunicationId}/trophyGroups/all/trophies${serviceParam}`;
    const earnedUrl = `${TROPHY_BASE_URL}/v1/users/me/npCommunicationIds/${game.npCommunicationId}/trophyGroups/all/trophies${serviceParam}`;
    const [definitionsResp, earnedResp] = await Promise.all([
      this.apiCall(definitionsUrl),
      this.apiCall(earnedUrl)
    ]);
    const earnedMap = /* @__PURE__ */ new Map();
    for (const t of earnedResp.trophies) {
      earnedMap.set(t.trophyId, {
        earned: !!t.earned,
        earnedDateTime: t.earnedDateTime || null
      });
    }
    const trophies = definitionsResp.trophies.map(
      (def) => {
        var _a, _b;
        const earned = earnedMap.get(def.trophyId);
        const isEarned = (_a = earned == null ? void 0 : earned.earned) != null ? _a : false;
        let completedDate = null;
        if (isEarned && (earned == null ? void 0 : earned.earnedDateTime)) {
          completedDate = earned.earnedDateTime.split("T")[0];
        }
        return {
          name: (_b = def.trophyName) != null ? _b : `Trophy #${def.trophyId}`,
          type: def.trophyType || "bronze",
          completed: isEarned,
          completedDate
        };
      }
    );
    return {
      game: game.trophyTitleName,
      platform: this.mapPlatform(game.trophyTitlePlatform),
      status: this.determineStatus(game.progress),
      trophies
    };
  }
  mapPlatform(platform) {
    if (platform.includes("PSVITA") || platform.includes("PS Vita")) {
      return "PS Vita";
    }
    if (platform.includes("PS5")) return "PS5";
    if (platform.includes("PS4")) return "PS4";
    if (platform.includes("PS3")) return "PS3";
    return platform;
  }
  determineStatus(progress) {
    if (progress >= 100) return "completed";
    if (progress > 0) return "in-progress";
    return "backlog";
  }
};

// src/settings.ts
var AchievementTrackerSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("General").setHeading();
    new import_obsidian2.Setting(containerEl).setName("Games folder").setDesc(
      "Folder where game notes are stored. Will be created if it doesn't exist."
    ).addText(
      (text) => text.setPlaceholder("Games").setValue(this.plugin.settings.gamesFolder).onChange(async (value) => {
        this.plugin.settings.gamesFolder = value || "Games";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Default platform").setDesc("Default platform when adding a new game.").addDropdown(
      (dropdown) => dropdown.addOptions({
        PS5: "PS5",
        PS4: "PS4",
        PS3: "PS3",
        "PS Vita": "PS Vita"
      }).setValue(this.plugin.settings.defaultPlatform).onChange(async (value) => {
        this.plugin.settings.defaultPlatform = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("PSN").setHeading();
    const instructions = containerEl.createDiv({ cls: "at-psn-instructions" });
    instructions.createEl("p", { text: "To import trophies from PSN, you need an NPSSO token:" });
    const ol = instructions.createEl("ol");
    ol.createEl("li", { text: "Sign in at store.playstation.com" });
    const step2 = ol.createEl("li");
    step2.appendText("Visit ");
    step2.createEl("code", { text: "https://ca.account.sony.com/api/v1/ssocookie" });
    ol.createEl("li", { text: 'Copy the "npsso" value from the JSON response' });
    ol.createEl("li", { text: "Paste it in the field below" });
    new import_obsidian2.Setting(containerEl).setName("NPSSO token").setDesc("Your PSN authentication token.").addText(
      (text) => text.setPlaceholder("Paste your NPSSO token here").setValue(this.plugin.settings.psnNpssoToken).onChange(async (value) => {
        this.plugin.settings.psnNpssoToken = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Test connection").setDesc("Verify that your NPSSO token is valid.").addButton(
      (btn) => btn.setButtonText("Test connection").onClick(async () => {
        const token = this.plugin.settings.psnNpssoToken;
        if (!token) {
          new import_obsidian2.Notice("Please enter an NPSSO token first.");
          return;
        }
        btn.setButtonText("Testing...");
        btn.setDisabled(true);
        try {
          const psnService = new PsnService();
          await psnService.testConnection(token);
          new import_obsidian2.Notice("PSN connection successful!");
        } catch (e) {
          const message = e instanceof Error ? e.message : "Unknown error";
          new import_obsidian2.Notice(
            `PSN connection failed: ${message}`
          );
        } finally {
          btn.setButtonText("Test connection");
          btn.setDisabled(false);
        }
      })
    );
  }
};

// src/views/tracker-view.ts
var import_obsidian11 = require("obsidian");

// src/constants.ts
var VIEW_TYPE_TRACKER = "trophy-tracker-view";
var TROPHY_ICONS = {
  platinum: "gem",
  gold: "trophy",
  silver: "award",
  bronze: "medal"
};
var TROPHY_COLORS = {
  platinum: "#7b9cc2",
  gold: "#cd9a10",
  silver: "#a8a8a8",
  bronze: "#cd7f32"
};
var TROPHY_TYPE_ORDER = {
  platinum: 0,
  gold: 1,
  silver: 2,
  bronze: 3
};

// src/services/frontmatter-parser.ts
var import_obsidian3 = require("obsidian");
async function readGameFrontmatter(app, file) {
  const content = await app.vault.read(file);
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  try {
    const data = (0, import_obsidian3.parseYaml)(match[1]);
    if (!data || !data.game || !Array.isArray(data.trophies)) return null;
    return {
      game: data.game,
      platform: data.platform || "PS5",
      status: data.status || "backlog",
      trophies: data.trophies.map(
        (t) => ({
          name: t.name || "",
          type: t.type || "bronze",
          completed: !!t.completed,
          completedDate: t.completedDate || null
        })
      )
    };
  } catch (e) {
    return null;
  }
}
async function updateGameFrontmatter(app, file, mutator) {
  await app.fileManager.processFrontMatter(file, mutator);
}
function buildGameNoteContent(data) {
  const yaml = (0, import_obsidian3.stringifyYaml)({
    game: data.game,
    platform: data.platform,
    status: data.status,
    trophies: data.trophies.map((t) => ({
      name: t.name,
      type: t.type,
      completed: t.completed,
      completedDate: t.completedDate
    }))
  });
  return `---
${yaml}---

## Notes
`;
}

// src/services/game-service.ts
var GameService = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  async getAllGames() {
    const folder = this.settings.gamesFolder;
    const files = this.app.vault.getMarkdownFiles().filter(
      (f) => f.path.startsWith(folder + "/")
    );
    const entries = [];
    for (const file of files) {
      const fm = await readGameFrontmatter(this.app, file);
      if (!fm) continue;
      const total = fm.trophies.length;
      const completed = fm.trophies.filter((t) => t.completed).length;
      entries.push({
        file,
        frontmatter: fm,
        totalTrophies: total,
        completedTrophies: completed,
        completionPercent: total > 0 ? Math.round(completed / total * 100) : 0
      });
    }
    return entries.sort((a, b) => a.frontmatter.game.localeCompare(b.frontmatter.game));
  }
  async createGame(data) {
    const folder = this.settings.gamesFolder;
    const folderExists = this.app.vault.getAbstractFileByPath(folder);
    if (!folderExists) {
      await this.app.vault.createFolder(folder);
    }
    const safeName = data.game.replace(/[\\/:*?"<>|]/g, "-");
    const path = `${folder}/${safeName}.md`;
    const content = buildGameNoteContent(data);
    return await this.app.vault.create(path, content);
  }
  async deleteGame(file) {
    await this.app.fileManager.trashFile(file);
  }
  async toggleTrophy(file, trophyName) {
    await updateGameFrontmatter(this.app, file, (fm) => {
      const data = fm;
      if (!Array.isArray(data.trophies)) return;
      const trophy = data.trophies.find(
        (t) => t.name === trophyName
      );
      if (!trophy) return;
      trophy.completed = !trophy.completed;
      trophy.completedDate = trophy.completed ? (/* @__PURE__ */ new Date()).toISOString().split("T")[0] : null;
      const allCompleted = data.trophies.every((t) => t.completed);
      if (allCompleted && data.trophies.length > 0) {
        data.status = "completed";
      } else if (data.status === "completed") {
        data.status = "in-progress";
      }
    });
  }
  async addTrophy(file, trophy) {
    await updateGameFrontmatter(this.app, file, (fm) => {
      const data = fm;
      if (!Array.isArray(data.trophies)) {
        data.trophies = [];
      }
      data.trophies.push({
        name: trophy.name,
        type: trophy.type,
        completed: trophy.completed,
        completedDate: trophy.completedDate
      });
    });
  }
  async removeTrophy(file, trophyName) {
    await updateGameFrontmatter(this.app, file, (fm) => {
      const data = fm;
      if (!Array.isArray(data.trophies)) return;
      data.trophies = data.trophies.filter(
        (t) => t.name !== trophyName
      );
    });
  }
  async updateTrophy(file, oldName, updated) {
    await updateGameFrontmatter(this.app, file, (fm) => {
      const data = fm;
      if (!Array.isArray(data.trophies)) return;
      const idx = data.trophies.findIndex(
        (t) => t.name === oldName
      );
      if (idx === -1) return;
      data.trophies[idx] = {
        name: updated.name,
        type: updated.type,
        completed: updated.completed,
        completedDate: updated.completedDate
      };
    });
  }
  async updateGameStatus(file, status) {
    await updateGameFrontmatter(this.app, file, (fm) => {
      const data = fm;
      data.status = status;
    });
  }
};

// src/ui/game-table.ts
var import_obsidian4 = require("obsidian");
var GameTableRenderer = class {
  constructor(container, games, callbacks) {
    this.container = container;
    this.games = games;
    this.callbacks = callbacks;
  }
  render() {
    this.container.empty();
    if (this.games.length === 0) {
      const empty = this.container.createDiv({ cls: "at-empty-state" });
      empty.createEl("p", {
        text: "No games tracked yet. Add a game to get started!"
      });
      return;
    }
    const table = this.container.createEl("table", { cls: "at-game-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    ["Game", "Platform", "Progress", "Trophies", "Status", ""].forEach(
      (text) => headerRow.createEl("th", { text })
    );
    const tbody = table.createEl("tbody");
    for (const game of this.games) {
      this.renderGameRow(tbody, game);
    }
  }
  renderGameRow(tbody, game) {
    const row = tbody.createEl("tr", { cls: "at-game-row" });
    const nameCell = row.createEl("td", { cls: "at-game-name" });
    const nameLink = nameCell.createEl("a", {
      text: game.frontmatter.game,
      cls: "at-game-link"
    });
    nameLink.addEventListener("click", (e) => {
      e.preventDefault();
      this.callbacks.onExpand(game.file);
    });
    row.createEl("td", { text: game.frontmatter.platform, cls: "at-platform" });
    const progressCell = row.createEl("td", { cls: "at-progress-cell" });
    const progressBar = progressCell.createDiv({ cls: "at-progress-bar" });
    const fill = progressBar.createDiv({ cls: "at-progress-fill" });
    fill.style.width = `${game.completionPercent}%`;
    if (game.completionPercent === 100) {
      fill.addClass("at-progress-complete");
    }
    progressCell.createEl("span", {
      text: `${game.completionPercent}%`,
      cls: "at-progress-text"
    });
    row.createEl("td", {
      text: `${game.completedTrophies}/${game.totalTrophies}`,
      cls: "at-trophy-count"
    });
    const statusCell = row.createEl("td");
    const select = statusCell.createEl("select", { cls: "at-status-select" });
    const statuses = [
      { value: "backlog", label: "Backlog" },
      { value: "in-progress", label: "In progress" },
      { value: "completed", label: "Completed" }
    ];
    for (const s of statuses) {
      const option = select.createEl("option", { text: s.label, value: s.value });
      if (s.value === game.frontmatter.status) {
        option.selected = true;
      }
    }
    select.addEventListener("change", () => {
      this.callbacks.onStatusChange(
        game.file,
        select.value
      );
    });
    const actionsCell = row.createEl("td", { cls: "at-actions" });
    const deleteBtn = actionsCell.createEl("button", {
      cls: "at-icon-btn at-delete-btn",
      attr: { "aria-label": "Delete game" }
    });
    (0, import_obsidian4.setIcon)(deleteBtn, "trash-2");
    deleteBtn.addEventListener("click", () => {
      this.callbacks.onDelete(game.file);
    });
  }
};

// src/ui/trophy-table.ts
var import_obsidian5 = require("obsidian");
var TrophyTableRenderer = class {
  constructor(container, game, callbacks) {
    this.container = container;
    this.game = game;
    this.callbacks = callbacks;
  }
  render() {
    this.container.empty();
    const header = this.container.createDiv({ cls: "at-trophy-header" });
    const backBtn = header.createEl("button", {
      cls: "at-icon-btn at-back-btn",
      attr: { "aria-label": "Back to game list" }
    });
    (0, import_obsidian5.setIcon)(backBtn, "arrow-left");
    backBtn.addEventListener("click", () => this.callbacks.onBack());
    header.createEl("h3", { text: this.game.frontmatter.game });
    const stats = header.createDiv({ cls: "at-trophy-stats" });
    stats.createEl("span", {
      text: `${this.game.completedTrophies}/${this.game.totalTrophies} trophies \xB7 ${this.game.completionPercent}%`
    });
    const toolbar = this.container.createDiv({ cls: "at-trophy-toolbar" });
    const addBtn = toolbar.createEl("button", {
      text: "Add trophy",
      cls: "at-btn at-btn-primary"
    });
    (0, import_obsidian5.setIcon)(addBtn, "plus");
    addBtn.prepend(addBtn.querySelector(".svg-icon"));
    addBtn.addEventListener("click", () => this.callbacks.onAdd());
    const trophies = this.sortTrophies(this.game.frontmatter.trophies);
    if (trophies.length === 0) {
      this.container.createDiv({ cls: "at-empty-state" }).createEl("p", {
        text: "No trophies yet. Add or import trophies to start tracking!"
      });
      return;
    }
    const table = this.container.createEl("table", { cls: "at-trophy-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    ["", "Type", "Trophy", "Date", ""].forEach(
      (text) => headerRow.createEl("th", { text })
    );
    const tbody = table.createEl("tbody");
    for (const trophy of trophies) {
      this.renderTrophyRow(tbody, trophy);
    }
  }
  sortTrophies(trophies) {
    return [...trophies].sort((a, b) => {
      var _a, _b;
      const typeOrder = ((_a = TROPHY_TYPE_ORDER[a.type]) != null ? _a : 99) - ((_b = TROPHY_TYPE_ORDER[b.type]) != null ? _b : 99);
      if (typeOrder !== 0) return typeOrder;
      if (a.completed !== b.completed) return a.completed ? 1 : -1;
      return a.name.localeCompare(b.name);
    });
  }
  renderTrophyRow(tbody, trophy) {
    const row = tbody.createEl("tr", {
      cls: `at-trophy-row ${trophy.completed ? "at-trophy-row--completed" : ""}`
    });
    const checkCell = row.createEl("td", { cls: "at-trophy-check" });
    const checkbox = checkCell.createEl("input", { type: "checkbox" });
    checkbox.checked = trophy.completed;
    checkbox.addEventListener(
      "change",
      () => this.callbacks.onToggle(trophy.name)
    );
    const typeCell = row.createEl("td", { cls: "at-trophy-type" });
    const iconSpan = typeCell.createEl("span", {
      cls: `at-trophy-icon at-trophy-icon-${trophy.type}`
    });
    const iconName = TROPHY_ICONS[trophy.type] || "circle";
    (0, import_obsidian5.setIcon)(iconSpan, iconName);
    iconSpan.style.color = TROPHY_COLORS[trophy.type] || "#888";
    typeCell.createEl("span", {
      text: trophy.type,
      cls: "at-trophy-type-label"
    });
    row.createEl("td", { text: trophy.name, cls: "at-trophy-name" });
    row.createEl("td", {
      text: trophy.completedDate || "\u2014",
      cls: "at-trophy-date"
    });
    const actionsCell = row.createEl("td", { cls: "at-actions" });
    const editBtn = actionsCell.createEl("button", {
      cls: "at-icon-btn",
      attr: { "aria-label": "Edit trophy" }
    });
    (0, import_obsidian5.setIcon)(editBtn, "pencil");
    editBtn.addEventListener("click", () => this.callbacks.onEdit(trophy));
    const deleteBtn = actionsCell.createEl("button", {
      cls: "at-icon-btn at-delete-btn",
      attr: { "aria-label": "Delete trophy" }
    });
    (0, import_obsidian5.setIcon)(deleteBtn, "trash-2");
    deleteBtn.addEventListener(
      "click",
      () => this.callbacks.onDelete(trophy.name)
    );
  }
};

// src/modals/add-game-modal.ts
var import_obsidian6 = require("obsidian");
var AddGameModal = class extends import_obsidian6.Modal {
  constructor(app, settings, onSubmit) {
    super(app);
    this.settings = settings;
    this.onSubmit = onSubmit;
    this.gameName = "";
    this.status = "backlog";
    this.platform = settings.defaultPlatform;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Add new game" });
    new import_obsidian6.Setting(contentEl).setName("Game name").addText(
      (text) => text.setPlaceholder("Enter game name").onChange((value) => {
        this.gameName = value;
      })
    );
    new import_obsidian6.Setting(contentEl).setName("Platform").addDropdown(
      (dropdown) => dropdown.addOptions({
        PS5: "PS5",
        PS4: "PS4",
        PS3: "PS3",
        "PS Vita": "PS Vita"
      }).setValue(this.platform).onChange((value) => {
        this.platform = value;
      })
    );
    new import_obsidian6.Setting(contentEl).setName("Status").addDropdown(
      (dropdown) => dropdown.addOptions({
        backlog: "Backlog",
        "in-progress": "In progress",
        completed: "Completed"
      }).setValue(this.status).onChange((value) => {
        this.status = value;
      })
    );
    new import_obsidian6.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Add game").setCta().onClick(() => {
        if (!this.gameName.trim()) {
          return;
        }
        void this.onSubmit({
          game: this.gameName.trim(),
          platform: this.platform,
          status: this.status,
          trophies: []
        });
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/modals/add-trophy-modal.ts
var import_obsidian7 = require("obsidian");
var AddTrophyModal = class extends import_obsidian7.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
    this.trophyName = "";
    this.trophyType = "bronze";
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Add trophy" });
    new import_obsidian7.Setting(contentEl).setName("Trophy name").addText(
      (text) => text.setPlaceholder("Enter trophy name").onChange((value) => {
        this.trophyName = value;
      })
    );
    new import_obsidian7.Setting(contentEl).setName("Type").addDropdown(
      (dropdown) => dropdown.addOptions({
        bronze: "Bronze",
        silver: "Silver",
        gold: "Gold",
        platinum: "Platinum"
      }).setValue(this.trophyType).onChange((value) => {
        this.trophyType = value;
      })
    );
    new import_obsidian7.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Add trophy").setCta().onClick(() => {
        if (!this.trophyName.trim()) return;
        void this.onSubmit({
          name: this.trophyName.trim(),
          type: this.trophyType,
          completed: false,
          completedDate: null
        });
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/modals/edit-trophy-modal.ts
var import_obsidian8 = require("obsidian");
var EditTrophyModal = class extends import_obsidian8.Modal {
  constructor(app, original, onSubmit) {
    super(app);
    this.original = original;
    this.onSubmit = onSubmit;
    this.trophyName = original.name;
    this.trophyType = original.type;
    this.completed = original.completed;
    this.completedDate = original.completedDate;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Edit trophy" });
    new import_obsidian8.Setting(contentEl).setName("Trophy name").addText(
      (text) => text.setValue(this.trophyName).onChange((value) => {
        this.trophyName = value;
      })
    );
    new import_obsidian8.Setting(contentEl).setName("Type").addDropdown(
      (dropdown) => dropdown.addOptions({
        bronze: "Bronze",
        silver: "Silver",
        gold: "Gold",
        platinum: "Platinum"
      }).setValue(this.trophyType).onChange((value) => {
        this.trophyType = value;
      })
    );
    new import_obsidian8.Setting(contentEl).setName("Completed").addToggle(
      (toggle) => toggle.setValue(this.completed).onChange((value) => {
        this.completed = value;
        if (value && !this.completedDate) {
          this.completedDate = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
        } else if (!value) {
          this.completedDate = null;
        }
      })
    );
    new import_obsidian8.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Save").setCta().onClick(() => {
        if (!this.trophyName.trim()) return;
        void this.onSubmit({
          name: this.trophyName.trim(),
          type: this.trophyType,
          completed: this.completed,
          completedDate: this.completedDate
        });
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/modals/import-modal.ts
var import_obsidian9 = require("obsidian");
var VALID_TYPES = ["bronze", "silver", "gold", "platinum"];
var ImportModal = class extends import_obsidian9.Modal {
  constructor(app, settings, onSubmit) {
    super(app);
    this.settings = settings;
    this.onSubmit = onSubmit;
    this.gameName = "";
    this.rawText = "";
    this.parsedTrophies = [];
    this.previewEl = null;
    this.platform = settings.defaultPlatform;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("at-import-modal");
    contentEl.createEl("h2", { text: "Import trophies" });
    new import_obsidian9.Setting(contentEl).setName("Game name").addText(
      (text) => text.setPlaceholder("Enter game name").onChange((value) => {
        this.gameName = value;
      })
    );
    new import_obsidian9.Setting(contentEl).setName("Platform").addDropdown(
      (dropdown) => dropdown.addOptions({
        PS5: "PS5",
        PS4: "PS4",
        PS3: "PS3",
        "PS Vita": "PS Vita"
      }).setValue(this.platform).onChange((value) => {
        this.platform = value;
      })
    );
    const formatInfo = contentEl.createDiv({ cls: "at-import-info" });
    formatInfo.createEl("p", {
      text: "Paste trophies, one per line. Supported formats:"
    });
    const list = formatInfo.createEl("ul");
    list.createEl("li", { text: "Trophy name, type" });
    list.createEl("li", { text: "Trophy name\\ttype (tab-separated)" });
    list.createEl("li", { text: "Trophy name (type auto-detected as bronze)" });
    formatInfo.createEl("p", {
      text: "Types: bronze, silver, gold, platinum",
      cls: "at-import-hint"
    });
    const textareaContainer = contentEl.createDiv({
      cls: "at-import-textarea-container"
    });
    const textarea = textareaContainer.createEl("textarea", {
      cls: "at-import-textarea",
      attr: {
        rows: "10",
        placeholder: "First blood, gold\nA new beginning	silver\nTrue champion, platinum\nEasy trophy"
      }
    });
    textarea.addEventListener("input", () => {
      this.rawText = textarea.value;
    });
    const buttonRow = contentEl.createDiv({ cls: "at-import-buttons" });
    const parseBtn = buttonRow.createEl("button", {
      text: "Parse & preview",
      cls: "at-btn"
    });
    parseBtn.addEventListener("click", () => {
      this.parsedTrophies = this.parseTrophyText(this.rawText);
      this.renderPreview();
    });
    const importBtn = buttonRow.createEl("button", {
      text: "Import",
      cls: "at-btn at-btn-primary"
    });
    importBtn.addEventListener("click", () => {
      if (!this.gameName.trim()) {
        new import_obsidian9.Notice("Please enter a game name.");
        return;
      }
      if (this.parsedTrophies.length === 0) {
        this.parsedTrophies = this.parseTrophyText(this.rawText);
      }
      if (this.parsedTrophies.length === 0) {
        new import_obsidian9.Notice("No trophies to import. Check your input format.");
        return;
      }
      void this.onSubmit({
        game: this.gameName.trim(),
        platform: this.platform,
        status: "backlog",
        trophies: this.parsedTrophies
      });
      new import_obsidian9.Notice(
        `Imported ${this.parsedTrophies.length} trophies for "${this.gameName.trim()}".`
      );
      this.close();
    });
    this.previewEl = contentEl.createDiv({ cls: "at-import-preview" });
  }
  parseTrophyText(text) {
    var _a;
    const lines = text.split("\n").map((l) => l.trim()).filter((l) => l.length > 0);
    const trophies = [];
    for (const line of lines) {
      let name;
      let type = "bronze";
      if (line.includes("	")) {
        const parts = line.split("	");
        name = parts[0].trim();
        const typePart = (_a = parts[1]) == null ? void 0 : _a.trim().toLowerCase();
        if (typePart && VALID_TYPES.includes(typePart)) {
          type = typePart;
        }
      } else if (line.includes(",")) {
        const lastComma = line.lastIndexOf(",");
        const possibleType = line.substring(lastComma + 1).trim().toLowerCase();
        if (VALID_TYPES.includes(possibleType)) {
          name = line.substring(0, lastComma).trim();
          type = possibleType;
        } else {
          name = line;
        }
      } else {
        name = line;
        if (line.toLowerCase().includes("platinum")) {
          type = "platinum";
        }
      }
      if (name) {
        trophies.push({
          name,
          type,
          completed: false,
          completedDate: null
        });
      }
    }
    return trophies;
  }
  renderPreview() {
    if (!this.previewEl) return;
    this.previewEl.empty();
    if (this.parsedTrophies.length === 0) {
      this.previewEl.createEl("p", {
        text: "No trophies parsed. Check your input.",
        cls: "at-import-warning"
      });
      return;
    }
    this.previewEl.createEl("p", {
      text: `Parsed ${this.parsedTrophies.length} trophies:`
    });
    const table = this.previewEl.createEl("table", {
      cls: "at-trophy-table at-import-preview-table"
    });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    ["Name", "Type"].forEach((h) => headerRow.createEl("th", { text: h }));
    const tbody = table.createEl("tbody");
    for (const t of this.parsedTrophies) {
      const row = tbody.createEl("tr");
      row.createEl("td", { text: t.name });
      row.createEl("td", { text: t.type });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/modals/psn-import-modal.ts
var import_obsidian10 = require("obsidian");
var PsnImportModal = class extends import_obsidian10.Modal {
  constructor(app, settings, onImport) {
    super(app);
    this.settings = settings;
    this.onImport = onImport;
    this.games = [];
    this.selectedIds = /* @__PURE__ */ new Set();
    this.isImporting = false;
    this.contentArea = null;
    this.importBtn = null;
    this.importProgressEl = null;
    this.psnService = new PsnService();
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.addClass("at-psn-modal");
    contentEl.createEl("h2", { text: "Import from PSN" });
    this.contentArea = contentEl.createDiv({ cls: "at-psn-content" });
    await this.loadGames();
  }
  async loadGames() {
    this.renderLoading();
    try {
      this.games = await this.psnService.fetchUserGames(
        this.settings.psnNpssoToken
      );
      this.renderGameList();
    } catch (e) {
      const message = e instanceof Error ? e.message : "Failed to load games from PSN.";
      this.renderError(message);
    }
  }
  renderLoading() {
    if (!this.contentArea) return;
    this.contentArea.empty();
    const loading = this.contentArea.createDiv({ cls: "at-psn-loading" });
    loading.createEl("p", { text: "Loading your PSN library..." });
  }
  renderError(message) {
    if (!this.contentArea) return;
    this.contentArea.empty();
    const error = this.contentArea.createDiv({ cls: "at-psn-error" });
    error.createEl("p", { text: message });
    const retryBtn = error.createEl("button", {
      text: "Retry",
      cls: "at-btn"
    });
    retryBtn.addEventListener("click", () => {
      void this.loadGames();
    });
  }
  renderGameList() {
    if (!this.contentArea) return;
    this.contentArea.empty();
    const summary = this.contentArea.createDiv({ cls: "at-psn-summary" });
    summary.createEl("span", {
      text: `Found ${this.games.length} games on your PSN profile`
    });
    const selectAllBtn = summary.createEl("button", {
      text: "Select all",
      cls: "at-btn"
    });
    selectAllBtn.addEventListener("click", () => {
      if (this.selectedIds.size === this.games.length) {
        this.selectedIds.clear();
        selectAllBtn.textContent = "Select all";
      } else {
        for (const g of this.games) {
          this.selectedIds.add(g.npCommunicationId);
        }
        selectAllBtn.textContent = "Deselect all";
      }
      this.updateCheckboxes();
      this.updateImportButton();
    });
    const listContainer = this.contentArea.createDiv({
      cls: "at-psn-game-list"
    });
    for (const game of this.games) {
      this.renderGameRow(listContainer, game);
    }
    const importBar = this.contentArea.createDiv({
      cls: "at-psn-import-bar"
    });
    this.importProgressEl = importBar.createEl("span", {
      cls: "at-psn-import-progress"
    });
    this.importBtn = importBar.createEl("button", {
      text: "Import selected (0)",
      cls: "at-btn at-btn-primary"
    });
    this.importBtn.disabled = true;
    this.importBtn.addEventListener("click", () => {
      void this.importSelected();
    });
  }
  renderGameRow(container, game) {
    const row = container.createDiv({ cls: "at-psn-game-row" });
    row.dataset.id = game.npCommunicationId;
    const checkbox = row.createEl("input", {
      type: "checkbox",
      cls: "at-psn-checkbox"
    });
    checkbox.checked = this.selectedIds.has(game.npCommunicationId);
    const info = row.createDiv({ cls: "at-psn-game-info" });
    info.createDiv({
      text: game.trophyTitleName,
      cls: "at-psn-game-title"
    });
    const meta = info.createDiv({ cls: "at-psn-game-meta" });
    meta.createEl("span", {
      text: this.formatPlatform(game.trophyTitlePlatform)
    });
    const totalTrophies = game.definedTrophies.bronze + game.definedTrophies.silver + game.definedTrophies.gold + game.definedTrophies.platinum;
    const earnedTrophies = game.earnedTrophies.bronze + game.earnedTrophies.silver + game.earnedTrophies.gold + game.earnedTrophies.platinum;
    meta.createEl("span", {
      text: `${earnedTrophies}/${totalTrophies} trophies`
    });
    meta.createEl("span", { text: `${game.progress}%` });
    const progressBar = row.createDiv({ cls: "at-progress-bar at-psn-progress" });
    const fill = progressBar.createDiv({ cls: "at-progress-fill" });
    fill.style.width = `${game.progress}%`;
    if (game.progress >= 100) {
      fill.addClass("at-progress-complete");
    }
    const toggleSelection = () => {
      if (this.selectedIds.has(game.npCommunicationId)) {
        this.selectedIds.delete(game.npCommunicationId);
      } else {
        this.selectedIds.add(game.npCommunicationId);
      }
      checkbox.checked = this.selectedIds.has(game.npCommunicationId);
      row.toggleClass(
        "at-psn-game-row--selected",
        checkbox.checked
      );
      this.updateImportButton();
    };
    row.addEventListener("click", (e) => {
      if (e.target === checkbox) return;
      toggleSelection();
    });
    checkbox.addEventListener("change", () => {
      if (checkbox.checked) {
        this.selectedIds.add(game.npCommunicationId);
      } else {
        this.selectedIds.delete(game.npCommunicationId);
      }
      row.toggleClass(
        "at-psn-game-row--selected",
        checkbox.checked
      );
      this.updateImportButton();
    });
  }
  updateCheckboxes() {
    if (!this.contentArea) return;
    const rows = this.contentArea.querySelectorAll(".at-psn-game-row");
    rows.forEach((row) => {
      const id = row.dataset.id;
      const cb = row.querySelector("input[type=checkbox]");
      if (cb && id) {
        cb.checked = this.selectedIds.has(id);
        row.toggleClass(
          "at-psn-game-row--selected",
          cb.checked
        );
      }
    });
  }
  updateImportButton() {
    if (this.importBtn) {
      const count = this.selectedIds.size;
      this.importBtn.textContent = `Import selected (${count})`;
      this.importBtn.disabled = count === 0 || this.isImporting;
    }
  }
  async importSelected() {
    if (this.isImporting || this.selectedIds.size === 0) return;
    this.isImporting = true;
    this.updateImportButton();
    const selectedGames = this.games.filter(
      (g) => this.selectedIds.has(g.npCommunicationId)
    );
    const total = selectedGames.length;
    let imported = 0;
    let skipped = 0;
    for (let i = 0; i < selectedGames.length; i++) {
      const game = selectedGames[i];
      if (this.importProgressEl) {
        this.importProgressEl.textContent = `Importing ${i + 1} of ${total}...`;
      }
      try {
        const safeName = game.trophyTitleName.replace(
          /[\\/:*?"<>|]/g,
          "-"
        );
        const path = `${this.settings.gamesFolder}/${safeName}.md`;
        const existing = this.app.vault.getAbstractFileByPath(path);
        if (existing) {
          skipped++;
          continue;
        }
        const data = await this.psnService.fetchGameTrophies(
          this.settings.psnNpssoToken,
          game
        );
        await this.onImport(data);
        imported++;
        if (i < selectedGames.length - 1) {
          await this.delay(300);
        }
      } catch (e) {
        const message2 = e instanceof Error ? e.message : "Unknown error";
        new import_obsidian10.Notice(
          `Failed to import "${game.trophyTitleName}": ${message2}`
        );
      }
    }
    let message = `Imported ${imported} game${imported !== 1 ? "s" : ""}`;
    if (skipped > 0) {
      message += ` (${skipped} skipped \u2014 already exist)`;
    }
    new import_obsidian10.Notice(message);
    this.isImporting = false;
    this.close();
  }
  delay(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  formatPlatform(platform) {
    return platform.replace("PSVITA", "PS Vita");
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/views/tracker-view.ts
var ConfirmDeleteModal = class extends import_obsidian11.Modal {
  constructor(app, fileName, onConfirm) {
    super(app);
    this.fileName = fileName;
    this.onConfirm = onConfirm;
    this.confirmed = false;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("p", {
      text: `Delete "${this.fileName}" and all its trophy data?`
    });
    new import_obsidian11.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Delete").setWarning().onClick(async () => {
        this.confirmed = true;
        await this.onConfirm();
        this.close();
      })
    ).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TrackerView = class extends import_obsidian11.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.games = [];
    this.expandedGame = null;
    this.plugin = plugin;
    this.gameService = new GameService(plugin.app, plugin.settings);
  }
  getViewType() {
    return VIEW_TYPE_TRACKER;
  }
  getDisplayText() {
    return "Achievement tracker";
  }
  getIcon() {
    return "trophy";
  }
  async onOpen() {
    await this.refresh();
  }
  onClose() {
    this.contentEl.empty();
    return Promise.resolve();
  }
  async refresh() {
    this.gameService = new GameService(this.plugin.app, this.plugin.settings);
    this.games = await this.gameService.getAllGames();
    this.render();
  }
  render() {
    const container = this.contentEl;
    container.empty();
    container.addClass("at-container");
    const toolbar = container.createDiv({ cls: "at-toolbar" });
    const addGameBtn = toolbar.createEl("button", {
      text: "Add game",
      cls: "at-btn at-btn-primary"
    });
    (0, import_obsidian11.setIcon)(addGameBtn, "plus");
    addGameBtn.prepend(addGameBtn.querySelector(".svg-icon"));
    addGameBtn.addEventListener("click", () => this.openAddGameModal());
    const importBtn = toolbar.createEl("button", {
      text: "Import",
      cls: "at-btn"
    });
    (0, import_obsidian11.setIcon)(importBtn, "download");
    importBtn.prepend(importBtn.querySelector(".svg-icon"));
    importBtn.addEventListener("click", () => this.openImportModal());
    if (this.plugin.settings.psnNpssoToken) {
      const psnBtn = toolbar.createEl("button", {
        text: "PSN import",
        cls: "at-btn"
      });
      (0, import_obsidian11.setIcon)(psnBtn, "gamepad-2");
      psnBtn.prepend(psnBtn.querySelector(".svg-icon"));
      psnBtn.addEventListener("click", () => this.openPsnImportModal());
    }
    const popoutBtn = toolbar.createEl("button", {
      cls: "at-btn",
      attr: { "aria-label": "Open in popout window" }
    });
    (0, import_obsidian11.setIcon)(popoutBtn, "external-link");
    popoutBtn.addEventListener("click", () => {
      void this.plugin.activatePopoutView();
    });
    const content = container.createDiv({ cls: "at-content" });
    if (this.expandedGame) {
      const game = this.games.find(
        (g) => g.file.path === this.expandedGame.path
      );
      if (game) {
        new TrophyTableRenderer(content, game, {
          onToggle: (name) => {
            void this.handleToggleTrophy(game.file, name);
          },
          onEdit: (trophy) => this.openEditTrophyModal(game.file, trophy),
          onDelete: (name) => {
            void this.handleDeleteTrophy(game.file, name);
          },
          onAdd: () => this.openAddTrophyModal(game.file),
          onBack: () => {
            this.expandedGame = null;
            this.render();
          }
        }).render();
        return;
      }
      this.expandedGame = null;
    }
    new GameTableRenderer(content, this.games, {
      onExpand: (file) => {
        this.expandedGame = file;
        this.render();
      },
      onDelete: (file) => {
        this.handleDeleteGame(file);
      },
      onStatusChange: (file, status) => {
        void this.handleStatusChange(file, status);
      }
    }).render();
  }
  openAddGameModal() {
    new AddGameModal(this.app, this.plugin.settings, async (data) => {
      await this.gameService.createGame(data);
      await this.refresh();
    }).open();
  }
  openImportModal() {
    new ImportModal(this.app, this.plugin.settings, async (data) => {
      await this.gameService.createGame(data);
      await this.refresh();
    }).open();
  }
  openPsnImportModal() {
    new PsnImportModal(this.app, this.plugin.settings, async (data) => {
      await this.gameService.createGame(data);
      await this.refresh();
    }).open();
  }
  openAddTrophyModal(file) {
    new AddTrophyModal(this.app, async (trophy) => {
      await this.gameService.addTrophy(file, trophy);
      await this.refresh();
    }).open();
  }
  openEditTrophyModal(file, trophy) {
    new EditTrophyModal(this.app, trophy, async (updated) => {
      await this.gameService.updateTrophy(file, trophy.name, updated);
      await this.refresh();
    }).open();
  }
  async handleToggleTrophy(file, trophyName) {
    await this.gameService.toggleTrophy(file, trophyName);
    await this.refresh();
  }
  async handleDeleteTrophy(file, trophyName) {
    await this.gameService.removeTrophy(file, trophyName);
    await this.refresh();
  }
  handleDeleteGame(file) {
    new ConfirmDeleteModal(this.app, file.basename, async () => {
      var _a;
      await this.gameService.deleteGame(file);
      if (((_a = this.expandedGame) == null ? void 0 : _a.path) === file.path) {
        this.expandedGame = null;
      }
      await this.refresh();
    }).open();
  }
  async handleStatusChange(file, status) {
    await this.gameService.updateGameStatus(file, status);
    await this.refresh();
  }
};

// src/main.ts
var AchievementTrackerPlugin = class extends import_obsidian12.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_TRACKER,
      (leaf) => new TrackerView(leaf, this)
    );
    this.addRibbonIcon("trophy", "Open achievement tracker", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-achievement-tracker",
      name: "Open tracker",
      callback: () => {
        void this.activateView();
      }
    });
    this.addCommand({
      id: "import-trophies",
      name: "Import trophies from text",
      callback: () => {
        const service = new GameService(this.app, this.settings);
        new ImportModal(this.app, this.settings, async (data) => {
          await service.createGame(data);
          this.refreshTrackerView();
        }).open();
      }
    });
    this.addCommand({
      id: "open-achievement-tracker-popout",
      name: "Open tracker in popout window",
      callback: () => {
        void this.activatePopoutView();
      }
    });
    this.addCommand({
      id: "import-from-psn",
      name: "Import trophies from PSN",
      callback: () => {
        if (!this.settings.psnNpssoToken) {
          new import_obsidian12.Notice(
            "Please set your PSN NPSSO token in the plugin settings first."
          );
          return;
        }
        const service = new GameService(this.app, this.settings);
        new PsnImportModal(
          this.app,
          this.settings,
          async (data) => {
            await service.createGame(data);
            this.refreshTrackerView();
          }
        ).open();
      }
    });
    this.addSettingTab(new AchievementTrackerSettingTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian12.TFile && file.path.startsWith(this.settings.gamesFolder + "/")) {
          this.refreshTrackerView();
        }
      })
    );
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_TRACKER)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        await rightLeaf.setViewState({
          type: VIEW_TYPE_TRACKER,
          active: true
        });
        leaf = rightLeaf;
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async activatePopoutView() {
    const leaf = this.app.workspace.openPopoutLeaf();
    await leaf.setViewState({
      type: VIEW_TYPE_TRACKER,
      active: true
    });
    this.app.workspace.revealLeaf(leaf);
  }
  refreshTrackerView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_TRACKER);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view && typeof view.refresh === "function") {
        void view.refresh();
      }
    }
  }
};
